### ISSUE TITLE
Can't launch the .exe

### ISSUE THREAD

**Issue by Kouent** [StephenCasella/SoundCloud-Playlist-Sync#11]
Hi dude

I used the 1.0.0.36 perfectly, but when I try to launch the 2.4 or 2.3 version Soundcloud Playlist Sync.exe (in Application Files\Soundcloud Playlist Sync_2_0_0_8), nothing happens, and my explorer crashes (it doesnt answer, I need to force close it)
Also tried to launch it as administrator, still doesn't work

Can you help ?

Anyway, thanks for this awesome application, saved my little DJ life ! :)

Best reguards,
Kouent.

EDIT : worked by disabling Avast agents (can't say why they made my explorer crash though)

**Comment by mpratt14** [comment]
i had to do the same thing lol. there were previously versions where i did not have to do that (but the first run would hang, close, and reopen without control anyway). 

this is all due to the DeepScreen feature. just disable that and you can run it fine with all other avast features enabled.
