### ISSUE TITLE
Request - Store list of previously synced or be able to sync from saved list

### ISSUE THREAD

**Issue by Kaicastledine** [StephenCasella/SoundCloud-Playlist-Sync#14]
Hello,

Would it be possible to add in a way of syncing previously synced URLS to locations ?

Either the application store the history or even be able to input a list of URLS & Locations to sync ?

Regards

**Comment by mcprat** [comment]
First off, are you using the fork here? https://github.com/erwinkramer/SoundCloud-Playlist-Sync

Erwin's updated fork save the most recent URL you use to sync. Other than that, I recommend you have a text document with a list of URLs for your own reference.

I do not believe it is reasonable to use more than 1 URL at a time...

**Comment by Kaicastledine** [comment]
No so thank you for pointing that out.

Yes I'm already doing so just thought it might be useful however I know that this is a old tool.
