### ISSUE TITLE
Error Message Attempting to Download All Songs by Artist

### ISSUE THREAD

**Issue by Fart-Sniffer** [StephenCasella/SoundCloud-Playlist-Sync#15]
Started using 3.0.0.25 of this program just today and it struggled on an earlier 'download all songs by artist, but I just kept hitting sync and it eventually got them all.

This one however, hits a brick wall. I tried deleting the files and starting it again but it always stops at the same point.

http://imgur.com/a/EE2FE

I also had another playlist where it downloaded all 70 items, except one! I tried syncing again but it just doesn't like this particular item:

http://imgur.com/a/k2LoQ

Is it known for this program to encounter errors or am I just special? Despite running into the above errors, I'm really impressed with the design & functionality of this program. What a pain it would be to click that download button for each and every item in a playlist..

**Comment by erwinkramer** [comment]
Did u try this version https://github.com/erwinkramer/SoundCloud-Playlist-Sync/releases/tag/r3.0.0

**Comment by erwinkramer** [comment]
I see u already had that version. Can u join me on gitter: https://gitter.im/erwinkramer/SoundCloud-Playlist-Sync?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by Fart-Sniffer** [comment]
Thanks for the super quick response, I'm on gitter now.

**Comment by erwinkramer** [comment]
@Fart-Sniffer  I reworked the app so it double checks the IsDownloadable variable. This fixes the issue with the first list. Please update the app. 

Post an issue on the other branch if u still experience issues. :)

**Comment by Fart-Sniffer** [comment]
Thank You! Do you have a donate button somewhere?

**Comment by Fart-Sniffer** [comment]
Also, has this been your project from the start or do you run your thing parallel to others?

**Comment by erwinkramer** [comment]
paypal.me/r3verse you can donate here if u want. 

This has been further developed by me. The other guy started the project but has abandoned it since a few years and I've been improving it ever since.

**Comment by mcprat** [comment]
It may not make a difference, but I can see in your screenshots that concurrency is set to 5 (is that the default btw?). I used to get errors like that more often when the concurrency is a higher value. I recommend concurrency value of 1. It may go just a little slower, but I think it is less likely for the API to have issues with the connections and requests.

**Comment by mcprat** [comment]
For the track that is being picky in the second screenshot, try single track URL method or maybe like the track and download your likes. If you still have trouble, http://peggo.co is a good alternative for single tracks.
