### ISSUE TITLE
Shows error log on failed downloads needed

### ISSUE THREAD

**Issue by VonSandberg** [StephenCasella/SoundCloud-Playlist-Sync#4]
Hi,
at first of all thank you for brilliant piece of code which saving my time ;)

> **Problem** is when I try to download my playlist I'm getting an error *"Some of tracks failed to download. Please try again."* so I would like to know, which tracks failed. In an error message or in some log.txt in playlist folder.
Any Idea why they could failed? An extra copyright secure?

Thanks in advance, George

**Comment by StephenCasella** [comment]
Hi George. I've just pushed a set of revisions and am building a new binary release now. One of the included changes makes the application show you a list of songs that did not download in the error message when any songs fail to download. 

Songs will randomly fail to download from SoundCloud and there's not much we can do about it on the user end except try again; their API is flaky and so is their CDN, so every once in a while it will improperly serve up track stream sources and we just have to try again. The application is tuned to avoid throttling, so as far as I can tell it's just an availability issue.
