### ISSUE TITLE
New logo/icon and design of app [concept]

### ISSUE THREAD

**Issue by VonSandberg** [StephenCasella/SoundCloud-Playlist-Sync#5]
Hi again :smirk:
I had free afternoon today, so I did some graphics after a long time.
Nothing serious, I was just playing around with new logo for your app (more likely just icon) and app layout including new design similar to Microsoft Visual Studio 2013 and newer. [Check this out here](http://on.be.net/1c44b8I) on my Behance.net profile.
If you would be interested, don't hesitate contact me and I will send you all data what I have. And of course it will be for free :sunglasses:

**Comment by StephenCasella** [comment]
That is fantastic. Thanks for spending time on that. I'd love to get that into the app. Is this issue thread convenient enough for discussing the details or would you prefer email?

**Comment by VonSandberg** [comment]
Thanks, I just wanted to contribute with something :smirk:
Actually I don't mind if we'll use email communication or not. But maybe it would be better and safer way, so here is my email *nahlovsky.j@gmail.com*.
Could you please delete this comment after you read it. Cheers.

**Comment by StephenCasella** [comment]
Continuing discussion over email.

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi
