### ISSUE TITLE
When I try to download a playlist an error occurs

### ISSUE THREAD

**Issue by solvorn** [StephenCasella/SoundCloud-Playlist-Sync#9]
http://imgur.com/a56CSox

**Comment by erwinkramer** [comment]
Could possibly be already fixed by my fork (UTF8 Encoding is now enabled). Could you try again with my fork or tell me which song it was you tried to download?

**Comment by solvorn** [comment]
I can't remember exactly but I was using this playlist:
https://soundcloud.com/instantdata/sets/nyanpass
I tried using your fork and I got this error
http://imgur.com/LuLZ44T

**Comment by erwinkramer** [comment]
I recreated this issue and i'll fix this bug asap.

**Comment by solvorn** [comment]
Alright thanks!!

**Comment by erwinkramer** [comment]
I think i fixed this one, please test the newest release i'll put on in a minute.

**Comment by erwinkramer** [comment]
https://github.com/erwinkramer/SoundCloud-Playlist-Sync/releases/tag/r1.0.0.38

Please try this one and tell me if it works properly.

**Comment by solvorn** [comment]
It works
